services:
  postgres:
    image: postgres:16-alpine
    container_name: qa-dashboard-db
    environment:
      POSTGRES_USER: qauser
      POSTGRES_PASSWORD: qapassword
      POSTGRES_DB: qa_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qauser -d qa_dashboard"]
      interval: 10s
      timeout: 5s
      retries: 5

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qa-dashboard-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://qauser:qapassword@postgres:5432/qa_dashboard
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
